# Generated by Django 5.2.17 on 2026-09-02 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True, verbose_name='bestandsnaam')),
                ('source_kind', models.CharField(choices=[('uren', 'Uren'), ('rit', 'Ritten (RouteVision)'), ('relatie', 'Relaties'), ('werkbon_controle', 'Werkbonnen (volledigheidscontrole)')], db_index=True, max_length=32, verbose_name='bron')),
                ('size_bytes', models.BigIntegerField(verbose_name='bestandsgrootte (bytes)')),
                ('unchanged_polls', models.PositiveIntegerField(default=1, verbose_name='ongewijzigde metingen')),
                ('last_measured_at', models.DateTimeField(verbose_name='laatste meting')),
                ('status', models.CharField(choices=[('wachtend', 'Wachtend op stabiliteit'), ('stabiel', 'Stabiel'), ('verwerkt', 'Verwerkt')], db_index=True, default='wachtend', max_length=16, verbose_name='status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='verwerkt op')),
                ('row_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='aantal regels')),
                ('last_error', models.TextField(blank=True, verbose_name='laatste foutmelding')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='voor het eerst gezien')),
            ],
            options={
                'verbose_name': 'importbestand',
                'verbose_name_plural': 'importbestanden',
                'ordering': ('-last_measured_at', 'filename'),
            },
        ),
        migrations.CreateModel(
            name='Relatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='regelnummer')),
                ('code', models.CharField(db_index=True, max_length=32, verbose_name='code')),
                ('relatienaam', models.CharField(blank=True, max_length=255, verbose_name='relatienaam')),
                ('postcode', models.CharField(blank=True, max_length=16, verbose_name='postcode')),
                ('huisnr', models.CharField(blank=True, max_length=32, verbose_name='huisnr')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='e-mail')),
                ('telefoon', models.CharField(blank=True, max_length=64, verbose_name='telefoon')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatie_rows', to='matching.importedfile')),
            ],
            options={
                'verbose_name': 'relatie',
                'verbose_name_plural': 'relaties',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Rit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='regelnummer')),
                ('kenteken', models.CharField(db_index=True, max_length=32, verbose_name='kenteken')),
                ('bestuurder', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='bestuurder')),
                ('reis_van_de_dag', models.PositiveIntegerField(blank=True, null=True, verbose_name='reis van de dag')),
                ('reistype', models.CharField(blank=True, max_length=8, verbose_name='reistype')),
                ('vertrekdatum', models.DateField(blank=True, db_index=True, null=True, verbose_name='vertrekdatum')),
                ('vertrektijd', models.TimeField(blank=True, null=True, verbose_name='vertrektijd')),
                ('vertrekadres', models.CharField(blank=True, max_length=255, verbose_name='vertrekadres')),
                ('vertrekplaats', models.CharField(blank=True, max_length=128, verbose_name='vertrekplaats')),
                ('aankomstdatum', models.DateField(blank=True, null=True, verbose_name='aankomstdatum')),
                ('aankomsttijd', models.TimeField(blank=True, null=True, verbose_name='aankomsttijd')),
                ('aankomstadres', models.CharField(blank=True, max_length=255, verbose_name='aankomstadres')),
                ('aankomstplaats', models.CharField(blank=True, max_length=128, verbose_name='aankomstplaats')),
                ('duur', models.DurationField(blank=True, null=True, verbose_name='duur')),
                ('km_prive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='privé (km)')),
                ('co2_prive', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='privé CO2 (kg)')),
                ('km_zakelijk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='zakelijke (km)')),
                ('co2_zakelijk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='zakelijk CO2 (kg)')),
                ('km_woonwerk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='woon-werk (km)')),
                ('co2_woonwerk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='woon-werk CO2 (kg)')),
                ('km_totaal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='totaal (km)')),
                ('co2_totaal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='totaal CO2 (kg)')),
                ('max_snelheid', models.PositiveIntegerField(blank=True, null=True, verbose_name='maximum (km/u)')),
                ('max_snelheid_datum', models.DateField(blank=True, null=True, verbose_name='max. snelheid datum')),
                ('max_snelheid_tijd', models.TimeField(blank=True, null=True, verbose_name='max. snelheid tijd')),
                ('max_snelheid_adres', models.CharField(blank=True, max_length=255, verbose_name='max. snelheid adres')),
                ('max_snelheid_plaats', models.CharField(blank=True, max_length=128, verbose_name='max. snelheid stad')),
                ('eindstand_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='eindstand (km)')),
                ('opmerking', models.CharField(blank=True, max_length=255, verbose_name='opmerking')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rit_rows', to='matching.importedfile')),
            ],
            options={
                'verbose_name': 'rit',
                'verbose_name_plural': 'ritten',
                'ordering': ('vertrekdatum', 'kenteken', 'row_number'),
                'indexes': [models.Index(fields=['bestuurder', 'vertrekdatum'], name='matching_ri_bestuur_d097b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Uren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='regelnummer')),
                ('medewerker', models.CharField(db_index=True, max_length=32, verbose_name='medewerker')),
                ('naam', models.CharField(blank=True, max_length=128, verbose_name='naam')),
                ('werkbon', models.CharField(db_index=True, max_length=32, verbose_name='werkbon')),
                ('datum', models.DateField(db_index=True, verbose_name='datum')),
                ('aantal', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='aantal')),
                ('taak_code', models.CharField(blank=True, max_length=32, verbose_name='taak code')),
                ('taak_omschrijving', models.CharField(blank=True, max_length=255, verbose_name='taak omschrijving')),
                ('project_opdrachtgever_naam', models.CharField(blank=True, max_length=255, verbose_name='project opdrachtgever naam')),
                ('postcode', models.CharField(blank=True, max_length=16, verbose_name='postcode')),
                ('plaats', models.CharField(blank=True, max_length=128, verbose_name='plaats')),
                ('adres', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('begintijd', models.TimeField(blank=True, null=True, verbose_name='begintijd')),
                ('eindtijd', models.TimeField(blank=True, null=True, verbose_name='eindtijd')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uren_rows', to='matching.importedfile')),
            ],
            options={
                'verbose_name': 'urenregel',
                'verbose_name_plural': 'urenregels',
                'ordering': ('datum', 'medewerker', 'row_number'),
                'indexes': [models.Index(fields=['medewerker', 'datum'], name='matching_ur_medewer_8a8adf_idx')],
            },
        ),
        migrations.CreateModel(
            name='WerkbonControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='regelnummer')),
                ('werkbon', models.CharField(db_index=True, max_length=32, verbose_name='werkbon')),
                ('medewerker', models.CharField(db_index=True, max_length=32, verbose_name='medewerker')),
                ('datum', models.DateField(db_index=True, verbose_name='datum')),
                ('fase_status', models.CharField(choices=[('afgerond', 'Afgerond'), ('nog niet gestart', 'Nog niet gestart')], max_length=32, verbose_name='fase-status')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='werkbon_controle_rows', to='matching.importedfile')),
            ],
            options={
                'verbose_name': 'werkbon (controle)',
                'verbose_name_plural': 'werkbonnen (controle)',
                'ordering': ('datum', 'medewerker', 'werkbon'),
                'constraints': [models.UniqueConstraint(fields=('source_file', 'werkbon', 'medewerker', 'datum'), name='unique_werkbon_controle_per_file')],
            },
        ),
    ]
