# Generated by Django 5.2.17 on 2026-09-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToleranceRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiteit', models.CharField(max_length=128, unique=True, verbose_name='activiteit')),
                ('drempel_minuten', models.PositiveIntegerField(default=15, verbose_name='drempel (minuten)')),
            ],
            options={
                'verbose_name': 'tolerantieregel',
                'verbose_name_plural': 'tolerantietabel',
                'ordering': ('activiteit',),
            },
        ),
        migrations.CreateModel(
            name='BekendeLocatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('postcode', 'Postcode'), ('straat', 'Straatnaam')], db_index=True, max_length=16, verbose_name='herkenning')),
                ('waarde', models.CharField(help_text='Postcode (4104 AC) of straatnaam (Randweg) — huisnummer weglaten.', max_length=255, verbose_name='waarde')),
                ('soort', models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur')], max_length=1, verbose_name='SOORT')),
                ('label', models.CharField(max_length=255, verbose_name='omschrijving')),
                ('is_depot', models.BooleanField(default=False, help_text='Eigen magazijn/zaak: wordt vóór alle andere regels herkend.', verbose_name='is depot')),
            ],
            options={
                'verbose_name': 'bekende locatie',
                'verbose_name_plural': 'bekende locaties',
                'ordering': ('type', 'waarde'),
                'unique_together': {('type', 'waarde')},
            },
        ),
        migrations.CreateModel(
            name='Instelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meegereden_modus', models.CharField(choices=[('VAST', 'Vast — permanent aan één senior gekoppeld'), ('PERIODE', 'Periode — koppeltabel met geldigheidsperiode'), ('SYNTESS', 'Uit Syntess (nog niet beschikbaar)')], default='VAST', max_length=16, verbose_name='meegereden-modus')),
            ],
            options={
                'verbose_name': 'instelling',
                'verbose_name_plural': 'instellingen',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='instelling_is_singleton')],
            },
        ),
        migrations.CreateModel(
            name='Monteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=128, verbose_name='naam')),
                ('medewerker_nummer', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='personeelsnummer (Syntess)')),
                ('bestuurder_code', models.CharField(blank=True, help_text='Leeg laten voor een monteur die nooit onder een eigen code rijdt omdat hij altijd meerijdt.', max_length=128, verbose_name='bestuurderscode (RouteVision)')),
                ('kenteken', models.CharField(blank=True, max_length=32, verbose_name='kenteken')),
                ('actief', models.BooleanField(default=True, verbose_name='actief')),
                ('vaste_meerijder', models.ForeignKey(blank=True, help_text="De senior monteur wiens ritten de tijdlijn van deze monteur bepalen. Alleen gebruikt wanneer de meegereden-modus op 'Vast' staat.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaste_meerijders', to='matching.monteur', verbose_name='rijdt vast mee met')),
            ],
            options={
                'verbose_name': 'monteur',
                'verbose_name_plural': 'monteurs',
                'ordering': ('naam',),
            },
        ),
        migrations.CreateModel(
            name='MeegeredenKoppeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_van', models.DateField(verbose_name='geldig van')),
                ('datum_tot', models.DateField(blank=True, help_text='Leeg laten wanneer de koppeling nog loopt.', null=True, verbose_name='geldig tot en met')),
                ('junior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meegereden_als_junior', to='matching.monteur', verbose_name='monteur die meerijdt')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meegereden_als_senior', to='matching.monteur', verbose_name='rijdt mee met')),
            ],
            options={
                'verbose_name': 'meegereden-koppeling',
                'verbose_name_plural': 'meegereden-koppelingen',
                'ordering': ('junior', '-datum_van'),
            },
        ),
        migrations.CreateModel(
            name='Tijdblok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, verbose_name='datum')),
                ('volgorde', models.PositiveIntegerField(verbose_name='volgorde')),
                ('soort', models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur'), ('W', 'Werkbon'), ('?', 'Onbekend'), ('O', 'Onverklaard'), ('R', 'Reistijd')], max_length=1, verbose_name='SOORT')),
                ('start_tijd', models.DateTimeField(verbose_name='starttijd')),
                ('eind_tijd', models.DateTimeField(verbose_name='eindtijd')),
                ('duur_minuten', models.PositiveIntegerField(verbose_name='duur (minuten)')),
                ('omschrijving', models.CharField(blank=True, max_length=255, verbose_name='omschrijving')),
                ('adres', models.CharField(blank=True, max_length=512, verbose_name='adres')),
                ('werkbon', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='werkbon')),
                ('berekend_op', models.DateTimeField(auto_now=True, verbose_name='berekend op')),
                ('monteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tijdblokken', to='matching.monteur')),
            ],
            options={
                'verbose_name': 'tijdblok',
                'verbose_name_plural': 'tijdblokken',
                'ordering': ('datum', 'monteur', 'volgorde'),
            },
        ),
        migrations.AddConstraint(
            model_name='monteur',
            constraint=models.UniqueConstraint(condition=models.Q(('bestuurder_code', ''), _negated=True), fields=('bestuurder_code',), name='unique_bestuurder_code_when_set'),
        ),
        migrations.AddConstraint(
            model_name='meegeredenkoppeling',
            constraint=models.CheckConstraint(condition=models.Q(('junior', models.F('senior')), _negated=True), name='meegereden_junior_is_not_senior'),
        ),
        migrations.AddIndex(
            model_name='tijdblok',
            index=models.Index(fields=['monteur', 'datum'], name='matching_ti_monteur_b609ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tijdblok',
            unique_together={('monteur', 'datum', 'volgorde')},
        ),
    ]
