# Generated by Django 5.2.17 on 2026-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_seed_tolerantietabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='werkboncontrole',
            name='monteur_meegereden',
            field=models.CharField(blank=True, max_length=16, verbose_name='monteur meegereden'),
        ),
        migrations.AddField(
            model_name='werkboncontrole',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='werkboncontrole',
            name='reistijd',
            field=models.CharField(blank=True, max_length=32, verbose_name='reistijd'),
        ),
        migrations.AddField(
            model_name='werkboncontrole',
            name='tijd',
            field=models.TimeField(blank=True, null=True, verbose_name='tijd'),
        ),
        migrations.AddField(
            model_name='werkboncontrole',
            name='titel',
            field=models.CharField(blank=True, max_length=255, verbose_name='titel'),
        ),
        migrations.AddField(
            model_name='werkboncontrole',
            name='werktijd',
            field=models.CharField(blank=True, max_length=32, verbose_name='werktijd'),
        ),
    ]
