# Generated by Django 5.2.17 on 2026-09-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_werkboncontrole_monteur_meegereden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmotorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laatste_run_gestart_op', models.DateTimeField(blank=True, null=True, verbose_name='laatste run gestart op')),
                ('laatste_run_afgerond_op', models.DateTimeField(blank=True, null=True, verbose_name='laatste run afgerond op')),
                ('succes', models.BooleanField(blank=True, null=True, verbose_name='gelukt')),
                ('dagen_verwerkt', models.PositiveIntegerField(default=0, verbose_name='dagen verwerkt')),
                ('foutmelding', models.TextField(blank=True, verbose_name='foutmelding')),
            ],
            options={
                'verbose_name': 'matchmotor-status',
                'verbose_name_plural': 'matchmotor-status',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='matchmotor_status_is_singleton')],
            },
        ),
    ]
