# Generated by Django 5.2.17 on 2026-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_matchmotorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tijdblok',
            name='postcode',
            field=models.CharField(blank=True, db_index=True, max_length=6, verbose_name='postcode'),
        ),
        migrations.AddField(
            model_name='tijdblok',
            name='straat',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='straat'),
        ),
    ]
