# Generated by Django 5.2.17 on 2026-09-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_tijdblok_postcode_tijdblok_straat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bekendelocatie',
            name='soort',
            field=models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur'), ('P', 'Privé')], max_length=1, verbose_name='SOORT'),
        ),
        migrations.AlterField(
            model_name='tijdblok',
            name='soort',
            field=models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur'), ('P', 'Privé'), ('W', 'Werkbon'), ('?', 'Onbekend'), ('O', 'Onverklaard'), ('R', 'Reistijd')], max_length=1, verbose_name='SOORT'),
        ),
    ]
