# Generated by Django 5.2.17 on 2026-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_bekendelocatie_soort_alter_tijdblok_soort'),
    ]

    operations = [
        migrations.AddField(
            model_name='monteur',
            name='thuisadres',
            field=models.CharField(blank=True, default='', help_text='Straatnaam (huisnummer weglaten) of postcode van het huisadres. Leeg laten mag: stops bij hem thuis verschijnen dan gewoon in de tijdlijn, meestal als onverklaard, en zijn daar te corrigeren.', max_length=255, verbose_name='thuisadres'),
        ),
        migrations.AddField(
            model_name='monteur',
            name='thuisadres_type',
            field=models.CharField(choices=[('postcode', 'Postcode'), ('straat', 'Straatnaam')], default='straat', max_length=16, verbose_name='thuisadres herkenning'),
        ),
        migrations.AlterField(
            model_name='bekendelocatie',
            name='soort',
            field=models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur'), ('P', 'Privé'), ('T', 'Thuis')], max_length=1, verbose_name='SOORT'),
        ),
        migrations.AlterField(
            model_name='tijdblok',
            name='soort',
            field=models.CharField(choices=[('K', 'Klant'), ('L', 'Locatie'), ('C', 'Crediteur'), ('P', 'Privé'), ('T', 'Thuis'), ('W', 'Werkbon'), ('?', 'Onbekend'), ('O', 'Onverklaard'), ('R', 'Reistijd')], max_length=1, verbose_name='SOORT'),
        ),
    ]
