# Generated by Django 5.2.17 on 2026-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_monteur_thuisadres_monteur_thuisadres_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatie',
            name='klant_of_leverancier',
            field=models.CharField(blank=True, max_length=1, verbose_name='klant of leverancier'),
        ),
    ]
