# Generated by Django 5.2.17 on 2026-09-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_relatie_klant_of_leverancier'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monteur',
            constraint=models.CheckConstraint(condition=models.Q(('vaste_meerijder', models.F('id')), _negated=True), name='monteur_vaste_meerijder_is_not_self'),
        ),
    ]
